### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by lucaspicerni** [xaukael/ffs#1]
Hello! Sorry to bother you, but could you provide a basic "how to"? This module is exactly what I was looking for! But I couldn't make it work. Is it system agnostic?

**Comment by xaukael** [comment]
I have planned to make a how-to video at some point, but have not had the time.
I am usually hanging around the foundry discord if you want to ping me there for help where you are getting hung up.
https://discord.gg/foundryvtt

**Comment by SabreRunner** [comment]
I second this. This system is probably what I need to build my own more easily but I would like some kind of demonstration.

**Comment by xaukael** [comment]
I made a short youtube video and linked it at the top of the readme. I have morning voice and fumbled a bit, but I hope it helps.
