### ISSUE TITLE
Issues using as default option

### ISSUE THREAD

**Issue by BioNaota** [xaukael/ffs#10]
<img width="631" alt="image" src="https://github.com/xaukael/ffs/assets/163650086/bc771299-5c1f-4972-835f-bc9df5b8b5b0">
I've configured a character sheet with an image and put it for default option
<img width="1335" alt="image" src="https://github.com/xaukael/ffs/assets/163650086/48e4da3a-a55f-436b-b691-c1e21ae01eb4">
<img width="662" alt="image" src="https://github.com/xaukael/ffs/assets/163650086/5eec75f7-5bdf-4f65-a0ae-64be54a7e393">
I've edited the template, just for trying with some values as you can see in this 2 screeshots
<img width="506" alt="image" src="https://github.com/xaukael/ffs/assets/163650086/e3484452-f7aa-4bf6-9a2f-7a9ab356de2c">
I try to create a new actor
<img width="1355" alt="image" src="https://github.com/xaukael/ffs/assets/163650086/4530ff7b-50fb-4c9d-b740-220e72d04285">
And when it creates, all the values of the sheet are empty...

I'm making something wrong???? I cannot use the template with the values as a default sheet for new characters????

<img width="279" alt="image" src="https://github.com/xaukael/ffs/assets/163650086/2632a5da-c3ef-4cfb-ae4d-e718c3526d64">
If I apply as you see in the screeshot, then it loads perfectly
<img width="759" alt="image" src="https://github.com/xaukael/ffs/assets/163650086/786325d3-b589-43a7-9644-340c40cf6d02">

The thing on this is I want thant my player can use the freeform sheet without any intervention from myself...

Thank you!!!!

**Comment by xaukael** [comment]
This is how I intended templates to work. I recently added a context menu option on the template to apply the template to all actors of that type. I expected that the GM would generally do the template once and apply to all actors of that type during setup and not many times after. 
Do you have your players creating actors?
I could hook on actor creation to apply the template on create.
I could also allow template application by the user to actors they own.
Let me know what your thoughts on these options.

**Comment by BioNaota** [comment]
You’ve do a GREAT job, this must go in first order 🤣, in my opinion I cannot demmand you nothing, I asked this because I was supossing doing something wrong 👍🏻.

Now, opinion. If you want to improve this module, I think than the perfect option is to hook the actor to the template on the creation process or allow create an actor with the template directly if you can.

thank you very much for your atention and your work 👍🏻😉

**Comment by xaukael** [comment]
Out of town for the weekend. For now, just create new actors by using duplicate in the actor context menu on the template actor.

**Comment by BioNaota** [comment]
You’re the best, by the moment I let players crete actors normaly and later convert the sheets 👍🏻.

thank you!!
