### ISSUE TITLE
Unable to drag Items on to FreeForm sheet

### ISSUE THREAD

**Issue by adamglinder** [xaukael/ffs#13]
Foundry 12 328
Simple World Building system 0.8.2
Freeform 1.17.6

Used to be able to drag and drop items from compendium/Items tab, now items do not appear when dragged on to the sheet after last update? Might be a v12 issue,

**Comment by xaukael** [comment]
fixed in 1.17.7

**Comment by adamglinder** [comment]
Thank You!
