### ISSUE TITLE
I Can't Edit Some Fields

### ISSUE THREAD

**Issue by brunocalado** [xaukael/ffs#2]
Hi. Great module.

I can't edit some fields I added. Video 1.
https://user-images.githubusercontent.com/4999783/235474152-b9eff4c7-3298-496e-9fb2-fc5fbae88f4a.mp4

This is how I set up
![image](https://user-images.githubusercontent.com/4999783/235474254-a5e1e2b7-1cdd-46b1-b88e-aa1fd64bf150.png)

I'm using simple world

**Comment by xaukael** [comment]
try checking this box in the SWB settings 
![image](https://user-images.githubusercontent.com/37848032/235505820-438f3362-92ca-4687-b805-0b8ab5654583.png)

**Comment by brunocalado** [comment]
> 

It's checked.
![image](https://user-images.githubusercontent.com/4999783/235506327-27cc20b5-de9f-4f3b-827a-c557f1e7b6dd.png)

**Comment by brunocalado** [comment]
> Sorry, I meant uncheck.

I tried. But, the same problem.

If I change the Actor Sheet, it works.
If I change the Freeform Sheet I can't trigger the box to edit. 
But, the description field works.
![image](https://user-images.githubusercontent.com/4999783/235512246-2376dd96-c24d-4132-b992-be2d7bccb3ce.png)

**Comment by xaukael** [comment]
can you run this in the console and respond with the result?

`console.log(JSON.stringify(game.system.model.Actor, null, 2))`

**Comment by brunocalado** [comment]
> can you run this in the console and respond with the result?
> 
> `console.log(JSON.stringify(game.system.model.Actor, null, 2))`
```
{
  "character": {
    "biography": "",
    "health": {
      "value": 10,
      "min": 0,
      "max": 10
    },
    "power": {
      "value": 5,
      "min": 0,
      "max": 5
    },
    "attributes": {},
    "groups": {}
  }
}```

**Comment by xaukael** [comment]
That is the same thing I get with an unconfigured SWB world. Are you sure you have it configured right? I might have to poke around the SWB system a bit to figure out if SWB will work with my current implementation.

**Comment by brunocalado** [comment]
> That is the same thing I get with an unconfigured SWB world. Are you sure you have it configured right? I might have to poke around the SWB system a bit to figure out if SWB will work with my current implementation.

I can share what I did. But, all the changes I did are in the image in the top of the issue. 

I can make some tests if you want.

**Comment by xaukael** [comment]
did you define the template? 
https://discord.com/channels/170995199584108546/1037073983335563457/1069776773002313788

**Comment by xaukael** [comment]
I expect it is needed. Do that and then run this again `console.log(JSON.stringify(game.system.model.Actor, null, 2))`

**Comment by brunocalado** [comment]
> I expect it is needed. Do that and then run this again `console.log(JSON.stringify(game.system.model.Actor, null, 2))`

I have a game now. I test this tomorrow. Thank you.

**Comment by brunocalado** [comment]
> console.log(JSON.stringify(game.system.model.Actor, null, 2))

```
{
  "character": {
    "biography": "",
    "health": {
      "value": 10,
      "min": 0,
      "max": 10
    },
    "power": {
      "value": 5,
      "min": 0,
      "max": 5
    },
    "attributes": {},
    "groups": {}
  }
}
```

![image](https://user-images.githubusercontent.com/4999783/235727204-e4e96f52-bc65-406a-9992-e15aab3c0114.png)

**Comment by xaukael** [comment]
no, no. You need to define the SWB actor template

**Comment by brunocalado** [comment]
> no, no. You need to define the SWB actor template

I don't understand. I **Define as Template** and used a newly created actor.

**Comment by brunocalado** [comment]
> am not familiar with the structure of any of them.

I know about SWB, PBTA and Custom System Builder. But, I just tried on SWB

**Comment by xaukael** [comment]
Editing fields in SWB should be working in 1.14.0

**Comment by brunocalado** [comment]
Thank you.
