### ISSUE TITLE
Values of attributes created in SWB cannot be edited in FFS sheet

### ISSUE THREAD

**Issue by dirusulixes** [xaukael/ffs#5]
With FFS 1.14.1 and SWB 0.7.2 I can create a FFS actor template, populate the sheet with attributes and then have them shown in the FFS sheet, however values are not editable from the FFS sheet by clicking on them.

For example, in this case the charm attribute is shown correctly `@attibutes.Skills.charm.value` but left-clicking on hit does not open an edit dialog.

![image](https://user-images.githubusercontent.com/5693623/236354813-76a6e5cf-4654-4a49-95fd-cdfa72801ede.png)

**Comment by xaukael** [comment]
double click

**Comment by dirusulixes** [comment]
Sorry, yes, I meant I double left click, but nothing happens. 
Value entry works for attributes that are built-in by default, for example `@health.value`
![image](https://user-images.githubusercontent.com/5693623/236411485-fdc8939e-520a-49c6-baf4-7654a94e7eba.png)
but for something I added to the sheet like `@attributes.Skills.charm.value` double clicking does not bring up the value entry menu.

**Comment by xaukael** [comment]
just the world/db files, not your data or modules

**Comment by xaukael** [comment]
This has been fixed. I even added the ability to edit @name spans.
