### ISSUE TITLE
Weird issue with the sheet

### ISSUE THREAD

**Issue by Iemier** [xaukael/ffs#7]
Hey! So I've been getting a strange issue suddenly where trying to edit someone's sheet, or even when they try to edit it; people are getting a ping that says "You do not have permission to edit this person's sheet" or something to that effect, and it'll immediately close itself, I've been having troubles fixing this issue other than just starting over from scratch with a brand new sheet.

**Comment by xaukael** [comment]
Could you try to narrow down what sort of edits cause the issue?

I do not touch permissions at all, so I am struggling to narrow down what could be happening. 

What system are you using? Does it happen with no other modules enabled?

**Comment by Iemier** [comment]
From what I could tell, it had something to do with another form type trying to override it, I found that editing the json file in a text document and deleting a line of code (seemed) to fix the issue.
"core": {},
    "exportSource": {
      "world": "corruption-of-champions-a-heart-and-fur-custom-campaign",
      This is what was deleted to fix it, from what I could tell, but I still had to also delete  the original actor or the issue would persist to some extent.  I don't really know script all that well, so I'm not absolutely sure what was going on in the first place for the issue to even start, cause' for the first week or so of using it to plan out a campaign, I wasn't having issues.

**Comment by xaukael** [comment]
I have never once had someone tell me how they fixed an issue and that actually being useful in identifying the issue.

What json file? If you mean an export of an actor, deleting just that would likely break the JSON file completely, so I do not understand how that could fix the problem. Those lines have nothing to do with my module. I have no idea what you could mean by form type. You have not told me what system you are using or indicated whether this work with all other modules disabled.
