### ISSUE TITLE
Can`t create a text inside the sheet

### ISSUE THREAD

**Issue by marx6591** [xaukael/ffs#9]
UUncaught (in promise) DOMException: An invalid or illegal string was specified
    jQuery 3
    newSpan http://localhost:30000/modules/ffs/ffs.js:293
    jQuery 8
    render http://localhost:30000/modules/ffs/ffs.js:446
    jQuery 2
[jquery.min.js:2](http://localhost:30000/scripts/jquery.min.js)
    render http://localhost:30000/modules/ffs/ffs.js:447
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    jQuery 2
    (assíncrono: async)
        dispatch
        handle

**Comment by marx6591** [comment]
![image](https://github.com/xaukael/ffs/assets/28965717/b3a57846-c4ba-41ab-818b-737ef1160b89)

**Comment by xaukael** [comment]
Looks like `ontenteditable ="plaintext-only"` is not available in firefox. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

I guess I have to decide if I want to just allow rich text and risk some weird things happening for every browser or just firefox.

**Comment by xaukael** [comment]
I did it for everyone. Update to 1.17.5 and let me know if you encounter any other issues.
